Repository GeoNode/geonode-mapstore-client, pull requests merged in 2021-09, with the labels that each got.

#490 [3.3.x] Fix layer export plugin import
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
Labels: bug

#492 303 update filtered list
  geonode_mapstore_client/client/js/epics/favorite.js
Labels: enhancement

#491 Filters notification improvement
  geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_menu.less
  geonode_mapstore_client/client/themes/geonode/less/_variables.less
Labels: enhancement

#483 Broken user card inside legacy People page
  geonode_mapstore_client/client/themes/geonode/less/geonode-legacy.less
Labels: bug

#470 Some UI changes to the Share panel
  geonode_mapstore_client/client/js/components/Permissions/Permissions.jsx
  geonode_mapstore_client/client/js/components/Permissions/PermissionsRow.jsx
  geonode_mapstore_client/client/js/plugins/Share.jsx
  geonode_mapstore_client/client/js/plugins/share/ShareEmbedLink.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement

#494 Improvements to label with numbers of filters applied
  geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
  geonode_mapstore_client/client/themes/geonode/less/_menu.less
Labels: enhancement

#495 Rename "Details" to "Info"
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement

#496 Removing a favorite doesn't update the favorites list and the resource cannot be set as favorite again
  geonode_mapstore_client/client/js/components/ContentsEditable/TextEditable.jsx
  geonode_mapstore_client/client/js/epics/favorite.js
Labels: bug

#498 Assorted issues for the share plugin
  geonode_mapstore_client/client/themes/geonode/less/_share.less
Labels: bug

#504 Add owner in permissions list
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/Permissions/Permissions.jsx
Labels: enhancement

#503 Hide empty fields from the info tab
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
Labels: enhancement

#513 #512: Add GeoPackage format to layer wps downlaod configuration
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement, BackportNeeded, 3.3.x
