Repository GeoNode/geonode-mapstore-client, pull requests merged in 2021-07, with the labels that each got.

#286 Fix padding of detail / preview panel button
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement

#287 Download button inside documents editor
  geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx
Labels: enhancement

#288 Improve the positioning of the edit icons inside detail panel
  geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement

#290 detail panel alignments regression
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: bug

#291 Missing count for filter values
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
Labels: bug

#300 Add separator between datasets, docs and the rest of the presentational resources
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/themes/geonode/less/_action-navbar.less
Labels: enhancement

#289 Export button inside dataset editor
  geonode_mapstore_client/client/js/epics/gnviewer.js
  geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
  geonode_mapstore_client/client/js/plugins/index.js
Labels: enhancement

#292 Add favorites icon to detail panel
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
Labels: enhancement

#295 Extent filter doesn't trigger filter requests
  geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx
Labels: bug

#299 Fill "next" parameter with the current page on login
  geonode_mapstore_client/client/js/components/home/BrandNavbar.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement

#310 Editors menus
  geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx
  geonode_mapstore_client/client/js/components/Menu/MenuItem.js
  geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/Save.jsx
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
  geonode_mapstore_client/client/js/plugins/Share.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement

#322 Editor menus aren't respecting permissions
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: targets master

#336 Add Save button to Dataset editor
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/epics/gnviewer.js
Labels: enhancement

#346 311 info tab
  geonode_mapstore_client/client/js/components/DefinitionList/DefinitionList.jsx
  geonode_mapstore_client/client/js/components/DefinitionList/__test__/DefinitionList-test.jsx
  geonode_mapstore_client/client/js/components/DefinitionList/index.js
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/Tabs/Tabs.jsx
  geonode_mapstore_client/client/js/components/Tabs/__test__/Tabs-test.jsx
  geonode_mapstore_client/client/js/components/Tabs/index.js
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement

#349 [FIXES #344] rest_framework namespace and duplicate URLs
  geonode_mapstore_client/apps.py
  mapstore2_adapter/api/urls.py
Labels: BackportNeeded

#350 Enable Save and Save As button in create new Map Or Geostory
  geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx
  geonode_mapstore_client/client/js/selectors/gnresource.js
Labels: bug

#348 Reduce thumbnail size in detail panel and move title and author
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement

#362 Show only resource type in field tab, some tabs improvements
  geonode_mapstore_client/client/js/components/DefinitionList/DefinitionList.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: bug

#380 [Fixes #334] Implement support for MapStore annotations
  geonode_mapstore_client/client/js/apps/gn-catalogue.js
  geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx
  geonode_mapstore_client/client/js/components/ContentsEditable/ThumbnailEditable.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/js/utils/GNSearchUtils.js
  geonode_mapstore_client/client/package.json
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/themes/geonode/less/geonode.less
Labels: BackportNeeded

#377 Implement GeoApp for Dashboards
  geonode_mapstore_client/apps.py
  geonode_mapstore_client/client/js/actions/gnviewer.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/apps/gn-dashboard.js
  geonode_mapstore_client/client/js/apps/gn-geostory.js
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/epics/gnviewer.js
  geonode_mapstore_client/client/js/routes/DatasetViewer.jsx
  geonode_mapstore_client/client/js/utils/GNSearchUtils.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_base.less
  geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
  geonode_mapstore_client/client/version.txt
  geonode_mapstore_client/hooksets.py
  geonode_mapstore_client/templates/geonode-mapstore-client/dashboard_embed.html
  geonode_mapstore_client/templates/geonode-mapstore-client/geostory_embed.html
  geonode_mapstore_client/templates/geonode-mapstore-client/legacy/app_embed.html
  geonode_mapstore_client/templates/geonode-mapstore-client/legacy/app_list.html
  geonode_mapstore_client/templatetags/get_menu_json.py
  mapstore2_adapter/api/serializers.py
  mapstore2_adapter/conf.py
  mapstore2_adapter/context_processors.py
  mapstore2_adapter/geoapps/geostories/__init__.py
  mapstore2_adapter/geoapps/geostories/api/__init__.py
  mapstore2_adapter/geoapps/geostories/api/permissions.py
  mapstore2_adapter/geoapps/geostories/api/serializers.py
  mapstore2_adapter/geoapps/geostories/api/urls.py
  mapstore2_adapter/geoapps/geostories/api/views.py
  mapstore2_adapter/geoapps/geostories/migrations/0001_initial.py
  mapstore2_adapter/geoapps/geostories/migrations/0002_auto_20201015_1533.py
  mapstore2_adapter/geoapps/geostories/migrations/__init__.py
  mapstore2_adapter/geoapps/geostories/models.py
  mapstore2_adapter/geoapps/geostories/translation.py
  mapstore2_adapter/hooks.py
  mapstore2_adapter/plugins/serializers.py
Labels: BackportNeeded

#365 Remove card menu
  geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx
Labels: enhancement

#342 use href instead of url composition
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
Labels: bug

#373 Attributes detail tab
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/Table/Table.jsx
  geonode_mapstore_client/client/js/components/Table/index.js
  geonode_mapstore_client/client/js/components/Tabs/Tabs.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement
