Repository GeoNode/geonode-mapstore-client, pull requests merged in 2021-11, with the labels that each got.

#556 Make Sign In and Register button background transparent
  geonode_mapstore_client/client/themes/geonode/less/_menu.less
Labels: enhancement

#558 Add "View" button to cards in list view
  geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
Labels: enhancement

#596 Add base docs files and config
  geonode_mapstore_client/client/.gitignore
  geonode_mapstore_client/client/README.md
  geonode_mapstore_client/client/devServer.js
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/actions/gnsave.js
  geonode_mapstore_client/client/js/actions/gnsearch.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/Menu/Menu.js
  geonode_mapstore_client/client/js/epics/index.js
  geonode_mapstore_client/client/js/plugins/Save.jsx
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
  geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
  geonode_mapstore_client/client/js/selectors/config.js
  geonode_mapstore_client/client/js/utils/APIUtils.js
  geonode_mapstore_client/client/js/utils/CoordinatesUtils.js
  geonode_mapstore_client/client/js/utils/FileUtils.js
  geonode_mapstore_client/client/js/utils/MenuUtils.js
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/package.json
Labels: 4.0.0

#599 #598: Fullscreen does not work for portals
  geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
Labels: bug, 4.0.0

#557 Give more relevance to ationbar buttons
  geonode_mapstore_client/client/themes/geonode/less/_menu.less
  geonode_mapstore_client/client/themes/geonode/less/_variables.less
Labels: enhancement

#601 #595: Display permission options based on resource type allowed_perms.compact properties
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/Permissions/Permissions.jsx
  geonode_mapstore_client/client/js/components/Permissions/PermissionsRow.jsx
  geonode_mapstore_client/client/js/components/Permissions/__tests__/Permission-test.jsx
  geonode_mapstore_client/client/js/plugins/Share.jsx
  geonode_mapstore_client/client/js/plugins/__tests__/share-test.jsx
  geonode_mapstore_client/client/js/routes/Search.jsx
  geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js
  geonode_mapstore_client/client/js/selectors/resource.js
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement

#608 Create map from dataset should be available if the user has add permission and access to the resource
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: bug, 4.0.0

#612 Add loading spinner beside the "# resources found"
  geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
  geonode_mapstore_client/client/js/routes/Detail.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/js/routes/Search.jsx
Labels: enhancement

#613 Remove the thumbnail input field from the Save As plugin
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
  geonode_mapstore_client/client/js/plugins/save/SaveModal.jsx
Labels: enhancement
