Repository GeoNode/geonode-mapstore-client, pull requests merged in 2021-05, with the labels that each got.

#131 Client - Add configurable list of options inside the resource cards
  geonode_mapstore_client/client/js/components/home/CardGrid.jsx
  geonode_mapstore_client/client/js/components/home/ResourceCard.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/js/utils/MenuUtils.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/scss/_resource-card.scss
Labels: enhancement

#148 Client - Flickering Search bar in homepage when the resource cards grid is empty or filtered #98
  geonode_mapstore_client/client/js/routes/Home.jsx
Labels: bug

#143 [Fixes #141] Create New Apps button is enabled for Anonymous users
  geonode_mapstore_client/templates/geonode-mapstore-client/app_list.html
Labels: BackportNeeded

#154 Client - Improve layout of filter form #99
  geonode_mapstore_client/client/js/components/home/FilterForm.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/themes/geonode/scss/_filter-by-extent.scss
  geonode_mapstore_client/client/themes/geonode/scss/_filter-form.scss
  geonode_mapstore_client/client/themes/geonode/scss/_home-container.scss
Labels: enhancement

#140 Only show a notification on map and geostory Save action #134
  geonode_mapstore_client/client/js/actions/gnsave.js
  geonode_mapstore_client/client/js/epics/__tests__/gnsave-test.js
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/plugins/Save.jsx
  geonode_mapstore_client/client/js/reducers/__tests__/gnsave-test.js
  geonode_mapstore_client/client/js/reducers/gnsave.js
Labels: 2.1.x, enhancement

#155 145: Add check for resource permission
  geonode_mapstore_client/client/js/apps/gn-geostory.js
  geonode_mapstore_client/client/js/apps/gn-home.jsx
  geonode_mapstore_client/client/js/apps/gn-map.js
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
Labels: 2.1.x, enhancement

#165 Client - Apply button of filter panel is not visible if the hero is in the same page
  geonode_mapstore_client/client/js/routes/Home.jsx
Labels: bug

#163 Extent filters does not update after clicking on apply
  geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx
Labels: bug

#162 Client - Overflow of text in cards list shows horizontal scrollbar
  geonode_mapstore_client/client/themes/geonode/scss/_resource-card.scss
Labels: bug

#161 Client - Implement ActionNavbar plugin
  geonode_mapstore_client/client/README.md
  geonode_mapstore_client/client/js/components/ActionNavbar/ActionNavbar.jsx
  geonode_mapstore_client/client/js/components/ActionNavbar/__test__/ActionNavbar-test.jsx
  geonode_mapstore_client/client/js/components/ActionNavbar/index.jsx
  geonode_mapstore_client/client/js/components/Menu/BurgerMenu.jsx
  geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx
  geonode_mapstore_client/client/js/components/Menu/Menu.js
  geonode_mapstore_client/client/js/components/Menu/MenuItem.js
  geonode_mapstore_client/client/js/components/Menu/__test__/BurgerMenu-test.jsx
  geonode_mapstore_client/client/js/hooks/useLocalStorage.js
  geonode_mapstore_client/client/js/hooks/useResizeElement.js
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/js/utils/MenuUtils.js
  geonode_mapstore_client/client/themes/geonode/scss/_action-navbar.scss
  geonode_mapstore_client/client/themes/geonode/scss/_hero.scss
  geonode_mapstore_client/client/themes/geonode/scss/_sub-flat-menu.scss
  geonode_mapstore_client/client/themes/geonode/scss/geonode.scss
Labels: enhancement

#164 157: Read layers permissions from API v2 instead of using style-check and edit-check requests #160
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/actions/gnsave.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/apps/gn-geostory.js
  geonode_mapstore_client/client/js/apps/gn-map.js
  geonode_mapstore_client/client/js/apps/gn-viewer.js
  geonode_mapstore_client/client/js/epics/__tests__/gnsave-test.js
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/epics/index.js
  geonode_mapstore_client/client/js/plugins/Save.jsx
  geonode_mapstore_client/client/js/reducers/gnresource.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: BackportNeeded

#149 [Fixes #135] Refactor how resource permissions are set inside the mapstore client context
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Labels: BackportNeeded

#180 Graphics enhancements to detail panel
  geonode_mapstore_client/client/themes/geonode/scss/_details-panel.scss
Labels: enhancement

#179 Switch to API v2 for the retrieval of keywords, categories, regions and owners
  geonode_mapstore_client/client/js/api/geonode/v1/index.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/routes/Home.jsx
Labels: enhancement

#192 Client - Introduce perms property inside menus and filters form items configuration
  geonode_mapstore_client/client/README.md
  geonode_mapstore_client/client/js/components/home/CardGrid.jsx
  geonode_mapstore_client/client/js/utils/MenuUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/MenuUtils-test.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement

#198 Client - Some UI enhancements to the Filters panel
  geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/scss/_filter-form.scss
Labels: enhancement

#186 Client - Implement DetailViewer plugin
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/actions/gnviewer.js
  geonode_mapstore_client/client/js/apps/gn-viewer.js
  geonode_mapstore_client/client/js/components/ContentsEditable/TextEditable.jsx
  geonode_mapstore_client/client/js/components/ContentsEditable/ThumbnailEditable.jsx
  geonode_mapstore_client/client/js/components/ContentsEditable/index.js
  geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/ViewerLayout.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/js/reducers/gnresource.js
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/themes/geonode/scss/_details-panel.scss
Labels: enhancement

#207 #203: SaveAs is not working anymore after returning an error in the response
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/reducers/gnsave.js
Labels: Backport

#206 [Fixes #204]: Ceating a New GeoStory Displays a Network Error
  mapstore2_adapter/geoapps/geostories/api/serializers.py
Labels: BackportNeeded
