Repository GeoNode/geonode-mapstore-client, pull requests merged in 2021-12, with the labels that each got.

#633 502 unpublished filter option
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement, 4.0.0

#639 New catalog keeps pushing the list to top when scrolling with mouse wheel
  geonode_mapstore_client/client/js/plugins/DatasetsCatalog.jsx
Labels: bug, 4.0.0

#646 Client - Layer Settings Plugin
  geonode_mapstore_client/client/js/epics/index.js
  geonode_mapstore_client/client/js/plugins/LayerSettings.jsx
  geonode_mapstore_client/client/js/plugins/__tests__/LayerSettings-test.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/js/plugins/layersettings/BaseLayerSettings.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/GeneralSettings.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/GroupSettings.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/SettingsSection.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/VisibilitySettings.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/WMSLayerSettings.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/_tests_/BaseLayerSettings-test.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/_tests_/GeneralSettings-test.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/_tests_/GroupSettings-test.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/_tests_/SettingsSection-test.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/_tests_/VisibilitySettings-test.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/_tests_/WMSLayerSettings-test.jsx
  geonode_mapstore_client/client/js/utils/__tests__/APIUtils-test.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_layer-settings.less
  geonode_mapstore_client/client/themes/geonode/less/geonode.less
Labels: enhancement, 4.0.0

#650 Add visual style editor for map viewer
  geonode_mapstore_client/client/js/epics/index.js
  geonode_mapstore_client/client/js/epics/visualstyleeditor.js
  geonode_mapstore_client/client/js/plugins/DatasetsCatalog.jsx
  geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
  geonode_mapstore_client/client/js/plugins/layersettings/WMSLayerSettings.jsx
  geonode_mapstore_client/client/js/selectors/resource.js
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_layer-settings.less
  geonode_mapstore_client/client/themes/geonode/less/_visual-style-editor.less
  geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
Labels: 4.0.0

#632 480 improve thumbnail ux
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/MapThumbnail.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/js/reducers/gnsave.js
  geonode_mapstore_client/client/package.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement, 4.0.0

#675 Hide set map button in certain conditions
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
Labels: bug
