Repository GeoNode/geonode-mapstore-client, pull requests merged in 2021-06, with the labels that each got.

#187 Fix extent rendering when it crosses idl
  geonode_mapstore_client/client/js/components/FiltersForm/FilterByExtent.jsx
  geonode_mapstore_client/client/js/utils/GNCoordinatesUtils.js
Labels: bug

#188 Client - Misalignment between inline language selector and brand Navbar items #145
  geonode_mapstore_client/client/js/components/home/LanguageSelector.jsx
  geonode_mapstore_client/client/themes/geonode/scss/_action-navbar.scss
Labels: bug

#201 Client - Implement BrandNavbar plugin
  geonode_mapstore_client/client/js/plugins/BrandNavbar.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/js/utils/AppUtils.js
Labels: enhancement

#220 Set default tile size for WMS layers in map configurations
  mapstore2_adapter/plugins/geonode.py
Labels: BackportNeeded

#223 218: Add toolbar icons are not visible when a GeoStory is empty
  geonode_mapstore_client/client/themes/default/less/geonode.less
Labels: bug

#197 Show Featured Items
  geonode_mapstore_client/client/js/actions/gnsearch.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/home/FeaturedList.jsx
  geonode_mapstore_client/client/js/epics/gnsearch.js
  geonode_mapstore_client/client/js/reducers/gnsearch.js
  geonode_mapstore_client/client/js/routes/Detail.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/js/routes/Search.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_card-grid.less
  geonode_mapstore_client/client/themes/geonode/less/look.less
Labels: enhancement

#239 Client - Display number of active filters
  geonode_mapstore_client/client/js/components/home/FiltersMenu.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement

#212 Implement MediaViewer Plugin
  geonode_mapstore_client/client/js/apps/gn-viewer.js
  geonode_mapstore_client/client/js/components/ActionNavbar/__test__/ActionNavbar-test.jsx
  geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
  geonode_mapstore_client/client/js/components/MediaViewer/PdfViewer.jsx
  geonode_mapstore_client/client/js/components/MediaViewer/__tests__/Media-test.jsx
  geonode_mapstore_client/client/js/components/MediaViewer/__tests__/PdfViewer-test.jsx
  geonode_mapstore_client/client/js/components/MediaViewer/index.js
  geonode_mapstore_client/client/js/components/Menu/__test__/Menu-test.js
  geonode_mapstore_client/client/js/plugins/MediaViewer.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/js/reducers/__tests__/gnsave-test.js
  geonode_mapstore_client/client/js/utils/FileUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/FileUtils-test.js
  geonode_mapstore_client/client/package.json
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/default/less/geonode.less
  geonode_mapstore_client/client/themes/geonode/less/_media-viewer.less
  geonode_mapstore_client/client/themes/geonode/less/geonode.less
Labels: enhancement

#241 check for perms undefined
  geonode_mapstore_client/client/js/utils/MenuUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/MenuUtils-test.js
Labels: bug

#219 Client - Filter form sends requests when the value field is changed
  geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
  geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx
  geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FiltersForm-test.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement

#248 Client - Error on featured resources request
  geonode_mapstore_client/client/js/components/home/FeaturedList.jsx
Labels: bug

#246 Client - Create new map page workflow
  geonode_mapstore_client/client/js/actions/gnviewer.js
  geonode_mapstore_client/client/js/epics/__tests__/gnviewer-test.js
  geonode_mapstore_client/client/js/epics/gnviewer.js
  geonode_mapstore_client/client/js/routes/MapViewer.jsx
  geonode_mapstore_client/client/package.json
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/configs/map.json
Labels: enhancement

#243 Client - Create new GeoStory page workflow
  geonode_mapstore_client/client/js/actions/gnviewer.js
  geonode_mapstore_client/client/js/api/geonode/config/index.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/epics/__tests__/gnviewer-test.js
  geonode_mapstore_client/client/js/epics/gnviewer.js
  geonode_mapstore_client/client/js/routes/GeoStoryViewer.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement

#250 Client - enable SPA link for the viewer
  geonode_mapstore_client/client/js/components/home/ResourceCard.jsx
  geonode_mapstore_client/client/js/utils/GNSearchUtils.js
Labels: enhancement

#255 Client - Create new geostory does not show an empty story
  geonode_mapstore_client/client/js/epics/__tests__/gnviewer-test.js
  geonode_mapstore_client/client/js/epics/gnviewer.js
Labels: bug

#253 Client - SEO improvement - add meta tag in page
  geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
  geonode_mapstore_client/client/js/components/MetaTags/Meta.jsx
  geonode_mapstore_client/client/js/components/MetaTags/__tests__/Meta-test.jsx
  geonode_mapstore_client/client/js/components/MetaTags/index.js
  geonode_mapstore_client/client/js/plugins/MediaViewer.jsx
  geonode_mapstore_client/client/js/routes/DocumentViewer.jsx
  geonode_mapstore_client/client/js/routes/GeoStoryViewer.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/js/routes/LayerViewer.jsx
  geonode_mapstore_client/client/js/routes/MapViewer.jsx
  geonode_mapstore_client/client/js/utils/AppUtils.js
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Labels: enhancement

#259 Client - Seo: first the resource title, then site name
  geonode_mapstore_client/client/js/components/MetaTags/Meta.jsx
  geonode_mapstore_client/client/js/components/MetaTags/__tests__/Meta-test.jsx
  geonode_mapstore_client/client/js/routes/DocumentViewer.jsx
  geonode_mapstore_client/client/js/routes/GeoStoryViewer.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/js/routes/LayerViewer.jsx
  geonode_mapstore_client/client/js/routes/MapViewer.jsx
Labels: enhancement

#264 Client - Detail panel / viewer improvement
  geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement

#256 Client - Clear filters button doesn't clean the filters form
  geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
Labels: bug

#270 Client - add flag to button detail in navbar and rm link resource in viewer
  geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
Labels: enhancement

#214 A favorite icon will let the authenticated user add the resource to his favorites
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/apps/gn-home.jsx
  geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/home/FaIcon.jsx
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/reducers/gnresource.js
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement

#273 Client - Change the "Save As" button inside the save as window to "Save"
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
Labels: enhancement

#278 Add Save button to Document editor
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/epics/gnviewer.js
  geonode_mapstore_client/client/js/selectors/gnresource.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement

#285 Add hint on hover for the thumbnail editing inside the detail panel
  geonode_mapstore_client/client/js/components/ContentsEditable/ThumbnailEditable.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement
