Repository GeoNode/geonode-mapstore-client, pull requests merged in 2021-04, with the labels that each got.

#106 Update customization section of readme
  README.md
Labels: BackportNeeded

#107 [Backport 2.1.x] Update customization section of readme
  README.md
Labels: Backport

#127 Client - Filter panel state should be consistent with the latest user action
  geonode_mapstore_client/client/js/actions/gnfiltersPanel.js
  geonode_mapstore_client/client/js/apps/gn-home.jsx
  geonode_mapstore_client/client/js/reducers/gnfiltersPanel.js
  geonode_mapstore_client/client/js/routes/Detail.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
Labels: bug

#129 Client - Fix Filter form rerender
  geonode_mapstore_client/client/js/components/home/FilterForm.jsx
Labels: bug

#128 Client - Switch between grid and list of cards
  geonode_mapstore_client/client/js/components/home/CardGrid.jsx
  geonode_mapstore_client/client/js/components/home/FiltersMenu.jsx
  geonode_mapstore_client/client/js/components/home/ResourceCard.jsx
  geonode_mapstore_client/client/js/hooks/__tests__/useLocalStorage-test.js
  geonode_mapstore_client/client/js/hooks/useLocalStorage.js
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/themes/geonode/scss/_card-grid.scss
  geonode_mapstore_client/client/themes/geonode/scss/_filter-form.scss
Labels: enhancement

#133 Client - Add configurable menu option in the filter menu
  geonode_mapstore_client/client/js/components/app/Router.jsx
  geonode_mapstore_client/client/js/components/home/FilterForm.jsx
  geonode_mapstore_client/client/js/components/home/FiltersMenu.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/scss/_filter-menu.scss
Labels: enhancement

#139 Client - Uniform items object configuration for all menus
  geonode_mapstore_client/client/README.md
  geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx
  geonode_mapstore_client/client/js/components/Menu/Menu.js
  geonode_mapstore_client/client/js/components/Menu/MenuItem.js
  geonode_mapstore_client/client/js/components/Menu/__test__/DropdownList-test.jsx
  geonode_mapstore_client/client/js/components/Menu/__test__/Menu-test.js
  geonode_mapstore_client/client/js/components/Menu/__test__/MenuItem-test.js
  geonode_mapstore_client/client/js/components/Menu/index.js
  geonode_mapstore_client/client/js/components/app/Router.jsx
  geonode_mapstore_client/client/js/components/home/BrandNavbar.jsx
  geonode_mapstore_client/client/js/components/home/FiltersMenu.jsx
  geonode_mapstore_client/client/js/components/home/Footer.jsx
  geonode_mapstore_client/client/js/components/home/MenuIndex.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
  geonode_mapstore_client/client/js/utils/MenuUtils.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement
