Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-09, with the labels that each got.

#1170 #1168 Some issues with map layer style editing
  geonode_mapstore_client/client/js/epics/datasetscatalog.js
  geonode_mapstore_client/client/js/epics/layersettings.js
  geonode_mapstore_client/client/js/epics/visualstyleeditor.js
  geonode_mapstore_client/client/js/selectors/__tests__/mapsave-test.js
  geonode_mapstore_client/client/js/selectors/mapsave.js
  geonode_mapstore_client/client/js/selectors/resource.js
  geonode_mapstore_client/client/js/utils/LayoutUtils.js
Labels: bug, BackportNeeded, master

#1172 [Backport 4.x][Fixes #1168] Some issues with map layer style editing
  geonode_mapstore_client/client/js/epics/datasetscatalog.js
  geonode_mapstore_client/client/js/epics/layersettings.js
  geonode_mapstore_client/client/js/epics/visualstyleeditor.js
  geonode_mapstore_client/client/js/selectors/__tests__/mapsave-test.js
  geonode_mapstore_client/client/js/selectors/mapsave.js
  geonode_mapstore_client/client/js/selectors/resource.js
  geonode_mapstore_client/client/js/utils/LayoutUtils.js
Labels: bug, Backport, 4.x

#1175 [Fixes 1169] Update total when resource is removed from favorite
  geonode_mapstore_client/client/js/actions/gnsearch.js
  geonode_mapstore_client/client/js/epics/favorite.js
  geonode_mapstore_client/client/js/reducers/gnsearch.js
Labels: bug, BackportNeeded, master

#1176 [Fixes 1174] Error not correctly shown error
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
  geonode_mapstore_client/client/js/utils/ErrorUtils.js
Labels: bug, BackportNeeded, master

#1182 [Backport 4.x][Fixes 1169] Update total when resource is removed from favorite
  geonode_mapstore_client/client/js/actions/gnsearch.js
  geonode_mapstore_client/client/js/epics/favorite.js
  geonode_mapstore_client/client/js/reducers/gnsearch.js
Labels: bug, Backport, 4.x

#1184 [Fixes 1174] Error not correctly shown error (#1176)
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
  geonode_mapstore_client/client/js/utils/ErrorUtils.js
Labels: bug, Backport, 4.x

#1197 [Fixes 1195] Counter keeps increasing when favorite icon is clicked multiple times
  geonode_mapstore_client/client/js/epics/favorite.js
Labels: bug, BackportNeeded, 4.0.x, master

#1200 [Backport 4.0.x][Fixes 1195] Counter keeps increasing when favorite icon is clicked multiple times
  geonode_mapstore_client/client/js/epics/favorite.js
Labels: Backport, 4.0.x

#1204 [Fixes 1147] Theme override styles from customization app needs some improvement
  docs/customizations/theme.html
Labels: documentation, enhancement, BackportNeeded

#1206 [Backport 4.0.x][Fixes 1147] Theme override styles from customization app needs some improvement
  docs/customizations/theme.html
Labels: documentation, enhancement, Backport, 4.0.x

#1205 [Backport 4.0.x][Fixes #1144] Disable / hide the charts button if a user doesn't have enough perms on the dataset
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: Backport, 4.0.x

#1199 [Fixes 1177] Hide copy/clone option for users without permissions
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: BackportNeeded, 4.0.x, master

#1181 fix typo in utils.py
  geonode_mapstore_client/utils.py
Labels: BackportNeeded, 4.0.x, master

#1212 [Fixes #1211] Add THUMBNAIL_SIZE configurations to __GEONODE_CONFIG__
  geonode_mapstore_client/context_processors.py
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Labels: BackportNeeded

#1218 [Fixes 1177] Hide copy/clone option for users without permissions
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: Backport, 4.0.x

#1217 [Fixes 1216] Remove uploaded items from new importer upload list on refresh
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
Labels: BackportNeeded, master

#1214 [Fixes 1210] Configure the client to receive image properties from server
  geonode_mapstore_client/client/js/components/ContentsEditable/ThumbnailEditable.jsx
Labels: enhancement, BackportNeeded, master

#1180 [Fixes 1143] Add Hint on settings and style icons on editing map layer
  geonode_mapstore_client/client/js/plugins/LayerSettings.jsx
  geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: bug, BackportNeeded, 4.0.x, master
