Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-12, with the labels that each got.

#1344 [Fixes 1343] Add jsdocs for new resources grid plugin
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
Labels: documentation

#1330 [Fixes 1306] Annotations and add dataset form is not opened when info is showing
  geonode_mapstore_client/client/js/epics/gnresource.js
Labels: BackportNeeded, master

#1342 Added docs for custom pages
  tutorials/04-custom-page.md
Labels: documentation

#1350 [Fixes #1308] Clone option in the list view is missing on Maps for non admin users
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
Labels: BackportNeeded, master

#1352 [Backport 4.0.x][Fixes #1308] Clone option in the list view is missing on Maps for non admin users (#1350)
  geonode_mapstore_client/client/js/components/ActionButtons/ActionButtons.jsx
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: Backport, 4.0.x

#1353 [Backport 4.0.x][Fixes #1310] Some checkbox filter combinations fail (#1312)
  geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
Labels: bug, Backport, 4.0.x

#1354 [Backport 4.0.x][Fixes #1307] Manage permissions on group not respected (#1316)
  geonode_mapstore_client/client/js/selectors/resource.js
Labels: Backport, 4.0.x

#1355 [Backport 4.0.x][Fixes #1309] HTML tags in the title on pressing enter from the edit info form (#1322)
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: Backport, 4.0.x

#1356 [Backport 4.0.x][Fixes #1306] Annotations and add dataset form is not opened when info is showing (#1330)
  geonode_mapstore_client/client/js/epics/gnresource.js
Labels: Backport, 4.0.x

#1366 [Backport 4.0.x][Fixes #1305] Unable to upload GEOJSON files with .json extention (#1317)
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/utils/FileUtils.js
Labels: Backport, 4.0.x

#1368 [Fixes #1362] Broken pagination in profile page
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/themes/geonode/less/_base.less
Labels: BackportNeeded, master

#1369 [Fixes #1358] Preview is not automatically closed when a resource is deleted
  geonode_mapstore_client/client/js/plugins/DeleteResource.jsx
Labels: BackportNeeded, master

#1371 [Fixes #1372] Update docs and review templates
  .github/workflows/static.yml
  geonode_mapstore_client/client/README.md
  geonode_mapstore_client/client/docs-template/README.md
  geonode_mapstore_client/client/docs-template/publish.js
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Bold-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Bold-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Bold-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-BoldItalic-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-BoldItalic-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-BoldItalic-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Italic-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Italic-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Italic-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Light-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Light-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Light-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-LightItalic-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-LightItalic-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-LightItalic-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Regular-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Regular-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Regular-webfont.woff
  geonode_mapstore_client/client/docs-template/static/scripts/linenumber.js
  geonode_mapstore_client/client/docs-template/static/scripts/prettify/Apache-License-2.0.txt
  geonode_mapstore_client/client/docs-template/static/scripts/prettify/lang-css.js
  geonode_mapstore_client/client/docs-template/static/scripts/prettify/prettify.js
  geonode_mapstore_client/client/docs-template/static/styles/jsdoc-default.css
  geonode_mapstore_client/client/docs-template/static/styles/prettify-jsdoc.css
  geonode_mapstore_client/client/docs-template/static/styles/prettify-tomorrow.css
  geonode_mapstore_client/client/docs-template/tmpl/augments.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/container.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/details.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/example.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/examples.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/exceptions.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/layout.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/mainpage.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/members.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/method.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/modifies.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/params.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/properties.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/returns.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/source.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/tutorial.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/type.tmpl
  geonode_mapstore_client/client/js/plugins/DeleteResource.jsx
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/DownloadResource.jsx
  geonode_mapstore_client/client/js/plugins/LayerSettings.jsx
  geonode_mapstore_client/client/js/plugins/MediaViewer.jsx
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/js/plugins/Save.jsx
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
  geonode_mapstore_client/client/js/plugins/Sync.jsx
  geonode_mapstore_client/client/js/utils/AppUtils.js
  geonode_mapstore_client/client/package.json
  tutorials/07-custom-resources-page.md
  tutorials/index.json
Labels: documentation, backport-4.1.x, TestNeeded

#1375 [Backport 4.1.x][Fixes #1362] Broken pagination in profile page (#1368)
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/themes/geonode/less/_base.less
Labels: 4.1.x

#1374 [Backport 4.1.x][Fixes #1358] Preview is not automatically closed when a resource is deleted (#1369)
  geonode_mapstore_client/client/js/plugins/DeleteResource.jsx
Labels: 4.1.x

#1376 [Backport 4.1.x][Fixes #1372] Update docs and review templates (#1371)
  geonode_mapstore_client/client/README.md
  geonode_mapstore_client/client/docs-template/README.md
  geonode_mapstore_client/client/docs-template/publish.js
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Bold-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Bold-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Bold-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-BoldItalic-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-BoldItalic-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-BoldItalic-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Italic-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Italic-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Italic-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Light-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Light-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Light-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-LightItalic-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-LightItalic-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-LightItalic-webfont.woff
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Regular-webfont.eot
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Regular-webfont.svg
  geonode_mapstore_client/client/docs-template/static/fonts/OpenSans-Regular-webfont.woff
  geonode_mapstore_client/client/docs-template/static/scripts/linenumber.js
  geonode_mapstore_client/client/docs-template/static/scripts/prettify/Apache-License-2.0.txt
  geonode_mapstore_client/client/docs-template/static/scripts/prettify/lang-css.js
  geonode_mapstore_client/client/docs-template/static/scripts/prettify/prettify.js
  geonode_mapstore_client/client/docs-template/static/styles/jsdoc-default.css
  geonode_mapstore_client/client/docs-template/static/styles/prettify-jsdoc.css
  geonode_mapstore_client/client/docs-template/static/styles/prettify-tomorrow.css
  geonode_mapstore_client/client/docs-template/tmpl/augments.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/container.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/details.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/example.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/examples.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/exceptions.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/layout.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/mainpage.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/members.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/method.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/modifies.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/params.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/properties.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/returns.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/source.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/tutorial.tmpl
  geonode_mapstore_client/client/docs-template/tmpl/type.tmpl
  geonode_mapstore_client/client/js/plugins/DeleteResource.jsx
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/DownloadResource.jsx
  geonode_mapstore_client/client/js/plugins/LayerSettings.jsx
  geonode_mapstore_client/client/js/plugins/MediaViewer.jsx
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/js/plugins/Save.jsx
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
  geonode_mapstore_client/client/js/plugins/Sync.jsx
  geonode_mapstore_client/client/js/utils/AppUtils.js
  geonode_mapstore_client/client/package.json
  tutorials/07-custom-resources-page.md
  tutorials/index.json
Labels: 4.1.x

#1379 [Fixes #1378] Add extra_head block to the index and catalogue templates
  geonode_mapstore_client/templates/geonode-mapstore-client/catalogue.html
  geonode_mapstore_client/templates/index.html
Labels: backport-4.1.x
