Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-07, with the labels that each got.

#1063 [Fixes #1064] Expose supported upload file formats as configurations
  geonode_mapstore_client/context_processors.py
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Labels: BackportNeeded, 4.x, master

#1068 rename function to get dataset supported types
  geonode_mapstore_client/context_processors.py
Labels: BackportNeeded, 4.x, master

#1056 [Fixes 955] Blured icon images
  geonode_mapstore_client/client/js/components/MainErrorView/index.js
  geonode_mapstore_client/client/js/components/MainEventView/MainEventView.jsx
  geonode_mapstore_client/client/js/components/MainEventView/index.js
  geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
  geonode_mapstore_client/client/js/components/MediaViewer/__tests__/Media-test.jsx
  geonode_mapstore_client/client/js/routes/Viewer.jsx
  geonode_mapstore_client/client/package.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_media-viewer.less
Labels: enhancement, BackportNeeded, 4.x, master

#1070 [Fixes #1069] Use new config setting for supported dataset file types
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
Labels: enhancement, BackportNeeded, master

#1061 [Backport 4.x][Fixes 1053] Include base support for localization in gn-document app entry
  geonode_mapstore_client/client/js/apps/gn-document.js
  geonode_mapstore_client/client/package.json
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement, Backport, 4.x

#1087 [Fixes 1085] Spinner is missing during the upload phase
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
Labels: bug, BackportNeeded, master

#1082 [Fixes 1058] Problem with color picker in Bar and Pie chart
  geonode_mapstore_client/client/themes/geonode/less/_base.less
Labels: bug, BackportNeeded, master

#1075 [Fixes 1072] Dataset legend must show the dataset's title instead of Geoserver's layername
  geonode_mapstore_client/client/js/plugins/Legend.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: BackportNeeded, master

#1080 [Backport 4.x] [Fixes #1064] Expose supported upload file formats as configurations
  geonode_mapstore_client/context_processors.py
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Labels: Backport, 4.x

#1090 [Fixes 1089] Fix text overflow in resource Delete dialog box
  geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
Labels: bug, BackportNeeded, master

#1098 [Fixes 1097] Spinner should not keep spinning in INVALID state
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
Labels: bug, BackportNeeded, master

#1099 [Backport 4.x][Fixes #1089] Fix text overflow in resource Delete dialog box
  geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
Labels: bug, Backport, 4.x

#1101 [Backport 4.x][Fixes #1072] Dataset legend must show the dataset's title instead of Geoserver's layername
  geonode_mapstore_client/client/js/plugins/Legend.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: Backport, 4.x

#1102 [Backport 4.x][Fixes #1038] Reload catalogue after saving a resource
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
  geonode_mapstore_client/client/js/epics/gnresource.js
  geonode_mapstore_client/client/js/epics/gnsave.js
  geonode_mapstore_client/client/js/reducers/gnsearch.js
Labels: Backport, 4.x

#1107 Show some informative message when a GPKG is imported
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement, BackportNeeded, 4.x, master

#1111 [Backport 4.x][Fixes #1085] Spinner is missing during the upload phase
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
Labels: bug, Backport, 4.x

#1112 [Backport 4.x][Fixes #1097] Spinner should not keep spinning in INVALID state
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
Labels: bug, Backport, 4.x

#1116 [Fixes 1115] Upload progress for GKPG based on execution requests
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
  geonode_mapstore_client/client/js/utils/ErrorUtils.js
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
Labels: enhancement, 4.x, master

#1125 [Backport 4.x][Fixes 1115] Upload progress for GKPG based on execution requests
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
  geonode_mapstore_client/client/js/utils/ErrorUtils.js
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
Labels: enhancement, 4.x
