Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-04, with the labels that each got.

#894 Fixed translations
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: bug

#897 Rename Layers Catalog to Datasets Catalog
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: 4.0.x

#895 Added global extensions folder
  geonode_mapstore_client/client/package.json
  geonode_mapstore_client/context_processors.py
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Labels: investigation, 3.3.x, 4.0.x

#903 The UploadDatasetForm should POST "store_spatial_files=true" when uploading
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
Labels: bug, 4.0.x

#908 Enable KML format for WPS export of vector layers
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: 4.0.x, master

#914 Dataset uploads are not updated appropriately
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
Labels: bug, 4.0.x

#920 Irrelevant message in dataset style editor
  geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
Labels: bug, 4.0.x

#916 Add layer visibility toggle to legend component
  geonode_mapstore_client/client/js/plugins/Legend.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/themes/geonode/less/_legend.less
Labels: 4.0.x

#909 Added global extensions folder
  geonode_mapstore_client/client/package.json
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
  mapstore2_adapter/context_processors.py
  package.json
Labels: 3.3.x

#928 [Backport 4.x][Fixes #911] Irrelevant message in dataset style editor
  geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
Labels: bug

#927 [Backport 4.x][Fixes #910] Dataset uploads are not updated appropriately
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
Labels: bug

#912 Issues with filters: no debounce and dropdown closing on click
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/SelectInfiniteScroll/SelectInfiniteScroll.jsx
Labels: bug, 4.0.x

#936 #937: Pending copy exectutions are not updated correctly on page reload
  geonode_mapstore_client/client/js/epics/gnsearch.js
  geonode_mapstore_client/client/js/utils/ResourceServiceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceServiceUtils-test.js
Labels: BackportNeeded

#939 [Backport 4.x] #900: Issues with filters: no debounce and dropdown closing on click (#912)
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/SelectInfiniteScroll/SelectInfiniteScroll.jsx
Labels: Backport

#940 [Backport 4.x] #937: Pending copy exectutions are not updated correctly on page reload (#936)
  geonode_mapstore_client/client/js/epics/gnsearch.js
  geonode_mapstore_client/client/js/utils/ResourceServiceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceServiceUtils-test.js
Labels: Backport

#944 Clear filters button not well aligned and not visible
  geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx
  geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FiltersForm-test.jsx
  geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
Labels: bug, 4.0.x

#943 Truncate abstract inside the metadata table inside the info box
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement, 4.0.x

#949 [Backport 4.x][Fixes #919] Truncate abstract inside the metadata table inside the info box
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: enhancement, Backport

#948 [Backport 4.x][Fixes #933] Clear filters button not well aligned and not visible
  geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx
  geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FiltersForm-test.jsx
  geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
Labels: bug, Backport
