Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-05, with the labels that each got.

#952 Failing datasets uploads are generating double entries in the list of not processed upload
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
  geonode_mapstore_client/client/themes/geonode/less/_upload.less
Labels: bug, 4.0.x

#960 [Fixes #946] Autoclose info panel on single click on the map
  geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
  geonode_mapstore_client/client/js/epics/gnresource.js
Labels: 4.0.x

#963 [Backport 4.x][Fixes #947]: Show direct links and embed links inside Share panel
  geonode_mapstore_client/client/js/plugins/Share.jsx
  geonode_mapstore_client/client/js/plugins/share/SharePageLink.jsx
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/themes/geonode/less/_share.less
Labels: Backport, 4.0.x

#970 [Backport 4.x][Fixes #946] Autoclose info panel on single click on the map
  geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
  geonode_mapstore_client/client/js/epics/gnresource.js
Labels: Backport, 4.0.x

#975 [Backport 4.x][Fixes #942] Failing datasets uploads are generating double entries in the list of not processed upload
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
  geonode_mapstore_client/client/themes/geonode/less/_upload.less
Labels: bug, Backport, 4.0.x

#981 Expose mapstore's setViewer to allow for custom GFI panel
  geonode_mapstore_client/client/js/utils/AppUtils.js
Labels: 3.3.x

#972 [Fixes #973] Improve LOCKDOWN_GEONODE
  geonode_mapstore_client/client/js/api/geonode/user/index.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/utils/APIUtils.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
  geonode_mapstore_client/templatetags/apikey.py
Labels: Backport, 4.0.x

#988 [Fixes #987] Failing migration 0002_migrate_map_blob.py
  geonode_mapstore_client/migrations/0002_migrate_map_blob.py
Labels: BackportNeeded

#982 [Fixes #979] Expose mapstore's setViewer to allow for custom GFI panel
  geonode_mapstore_client/client/js/utils/AppUtils.js
Labels: enhancement, BackportNeeded, 4.x

#996 [Fixes 966] Provide visual feedback while loading filtered resources
  geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
  geonode_mapstore_client/client/themes/geonode/less/_menu.less
Labels: enhancement, BackportNeeded, 4.x, master

#997 [Fixes #964] info icon for not approved / not published resource shouldn't take a line
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
Labels: BackportNeeded, 4.x, master

#998 [Fixes #986] Anonymous users have an option of adding dataset and annotations to a map
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: BackportNeeded, 4.x, master

#1001 [Fixes #969] Add "with_resources" GET parameter on regions and categories endpoints
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
Labels: enhancement, BackportNeeded, 4.x, master

#989 [Backport 4.x][Fixes #987] Fix migration map blob (#988)
  geonode_mapstore_client/migrations/0002_migrate_map_blob.py
Labels: Backport, 4.x
