Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-11, with the labels that each got.

#1276 [Fixes 1267] Filter executionrequest by source
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
Labels: BackportNeeded, master

#1279 [Fixes 1278] Inconsistencies in group permissions search panel
  geonode_mapstore_client/client/js/plugins/Share.jsx
Labels: bug, BackportNeeded, master

#1282 [Backport 4.0.x][Fixes #1278] Inconsistencies in group permissions search panel
  geonode_mapstore_client/client/js/plugins/Share.jsx
Labels: bug, Backport, 4.0.x

#1284 [Backport 4.0.x][Fixes #1243] Show metadata page in Document view when preview is not available
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
  geonode_mapstore_client/client/js/components/MetadataPreview/MetadataPreview.jsx
  geonode_mapstore_client/client/js/components/MetadataPreview/index.js
  geonode_mapstore_client/client/js/epics/gnsearch.js
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement, Backport, 4.0.x

#1285 [Backport 4.0.x][Fixes 1268] Fix metadata view buttons bug (#1269)
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
Labels: bug, Backport, 4.0.x

#1288 [Fixes 1286] "style" is lowercase, while the other menu items have the second term uppercase
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
Labels: BackportNeeded, master

#1292 [Fixes 1291] The search box should use metadata_only=False
  geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html
Labels: BackportNeeded, master

#1299 [Fixes #1267] Filter executionrequest by source
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
Labels: Backport, 4.0.x

#1290 [Backport 4.0.x][Fixes 1249] Change Edit Layer style to Edit style
  geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: Backport, 4.0.x

#1311 [Backport 4.0.x][Fixes 1291] The search box should use metadata_only=False
  geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html
Labels: Backport, 4.0.x

#1294 [Fixes 1293] Empty catalogue page after navigating from viewer page
  geonode_mapstore_client/client/js/apps/gn-catalogue.js
  geonode_mapstore_client/client/js/apps/gn-dashboard.js
  geonode_mapstore_client/client/js/apps/gn-document.js
  geonode_mapstore_client/client/js/apps/gn-geostory.js
  geonode_mapstore_client/client/js/apps/gn-home.jsx
  geonode_mapstore_client/client/js/apps/gn-map.js
  geonode_mapstore_client/client/js/epics/gnsearch.js
  geonode_mapstore_client/client/js/utils/AppRoutesUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/AppRoutesUtils-test.js
Labels: bug, regression, master

#1312 [Fixes 1310] Some checkbox filter combinations fail
  geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
Labels: bug, investigation, BackportNeeded, master

#1316 [Fixes 1307] Manage permissions on group not respected
  geonode_mapstore_client/client/js/selectors/resource.js
Labels: investigation, BackportNeeded, master

#1317 [Fixes 1305] Unable to upload GEOJSON files with .json extention
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/utils/FileUtils.js
Labels: investigation, BackportNeeded, master

#1320 [Fixes 1303] Redirect users to Login page on accessing restricted pages
  geonode_mapstore_client/client/js/apps/gn-catalogue.js
  geonode_mapstore_client/client/js/apps/gn-dashboard.js
  geonode_mapstore_client/client/js/apps/gn-document.js
  geonode_mapstore_client/client/js/apps/gn-geostory.js
  geonode_mapstore_client/client/js/apps/gn-map.js
  geonode_mapstore_client/client/js/components/Router/Router.jsx
  geonode_mapstore_client/client/js/utils/AppRoutesUtils.js
Labels: BackportNeeded

#1324 [Fixes 1323] Disable management features from featured cards
  geonode_mapstore_client/client/js/components/FeaturedList/FeaturedList.jsx
  geonode_mapstore_client/client/js/routes/Home.jsx
Labels: BackportNeeded, master

#1322 [Fixes 1309] HTML tags in the title on pressing enter from the edit info form
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: BackportNeeded, 4.0.x, master

#1339 Refactor of details panel info
  geonode_mapstore_client/client/js/components/AuthorInfo/AuthorInfo.jsx
  geonode_mapstore_client/client/js/components/ContentsEditable/TextEditable.jsx
  geonode_mapstore_client/client/js/components/ContentsEditable/index.js
  geonode_mapstore_client/client/js/components/DefinitionList/DefinitionList.jsx
  geonode_mapstore_client/client/js/components/DefinitionList/__test__/DefinitionList-test.jsx
  geonode_mapstore_client/client/js/components/DefinitionList/index.js
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsResourcePreview.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsThumbnail.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/ThumbnailEditable.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/ThumbnailPreview.jsx
  geonode_mapstore_client/client/js/components/Tabs/Tabs.jsx
  geonode_mapstore_client/client/js/components/Tabs/__test__/Tabs-test.jsx
  geonode_mapstore_client/client/js/components/Tabs/index.js
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/js/utils/MenuUtils.js
  geonode_mapstore_client/client/js/utils/PluginsContextUtils.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fi-FI.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.hr-HR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
  geonode_mapstore_client/client/static/mapstore/translations/data.nl-NL.json
  geonode_mapstore_client/client/static/mapstore/translations/data.pt-PT.json
  geonode_mapstore_client/client/static/mapstore/translations/data.sk-SK.json
  geonode_mapstore_client/client/static/mapstore/translations/data.sv-SE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.vi-VN.json
  geonode_mapstore_client/client/static/mapstore/translations/data.zh-ZH.json
  geonode_mapstore_client/client/themes/geonode/less/_base.less
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
  geonode_mapstore_client/client/themes/geonode/less/_resources-grid.less
Labels: BackportNeeded, master, 4.1.x

#1337 [Fixes 1336] Deleting resources removes applied filters
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: investigation, regression, master

#1338 [Fixes 1335] Pagination buttons on empty catalogue page
  geonode_mapstore_client/client/js/components/Router/Router.jsx
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
Labels: regression, master
