Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-10, with the labels that each got.

#1232 [Fixes 1226] Embedded maps should have the timeline plugin
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement, BackportNeeded, master

#1222 [Backport 4.0.x][Fixes 1216] Remove uploaded items from new importer upload list on refresh
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
Labels: Backport, 4.0.x

#1223 [Fixes 1213] Avoid executing permissions request for anonymous users
  geonode_mapstore_client/client/js/epics/gnresource.js
Labels: master

#1252 Fix map cloning
  geonode_mapstore_client/migrations/0002_migrate_map_blob.py
Labels: BackportNeeded

#1241 [Backport 4.0.x][Fixes #1213] Avoid executing permissions request for anonymous users
  geonode_mapstore_client/client/js/epics/gnresource.js
Labels: Backport, 4.0.x

#1242 [Backport 4.0.x][Fixes 1226] Embedded maps should have the timeline plugin
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: enhancement, Backport, 4.0.x

#1248 [Fixes 1247] Move Remote Service under Add Resource
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/templatetags/get_menu_json.py
Labels: BackportNeeded, 4.0.x, master

#1250 [Fixes 1243] Show metadata page in Document view when preview is not available
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
  geonode_mapstore_client/client/js/components/MetadataPreview/MetadataPreview.jsx
  geonode_mapstore_client/client/js/components/MetadataPreview/index.js
  geonode_mapstore_client/client/js/epics/gnsearch.js
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement, BackportNeeded, 4.0.x, master

#1255 [Fixes 1254] Fix issue with upload failing when file extension is in uppercase
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/routes/UploadDocument.jsx
  geonode_mapstore_client/client/js/utils/FileUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/FileUtils-test.js
Labels: bug, BackportNeeded, master

#1251 [Fixes 1249] Change Edit Layer style to Edit style
  geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: bug, BackportNeeded, 4.0.x, master

#1225 [Fixes #1224] Change language on time series page not working
  geonode_mapstore_client/templates/geonode-mapstore-client/snippets/language_selector.html
Labels: BackportNeeded

#1261 [Fixes 1260] Adapt the client to use the new detail_url in dataset import
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
Labels: enhancement, BackportNeeded, master

#1269 [Fixes 1268] Fix metedata view buttons bug
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
Labels: bug, master

#1270 [Backport 4.0.x][Fixes #1247] Move Remote Service under Add Resource (#1248)
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/templatetags/get_menu_json.py
Labels: Backport, 4.0.x
