Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-08, with the labels that each got.

#1124 [Backport 4.x][Fixes 1108] Show some informative message when a GPKG is imported
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement, 4.x

#1126 [Fixes 1120] Wrong text for the dashbaord's successfully synced popup
  geonode_mapstore_client/client/js/epics/gnsync.js
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: bug, BackportNeeded, 4.x, master

#1134 [Backport 4.x][Fixes 1114] Favorites are broken
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/ActionNavbar/ActionNavbar.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/epics/favorite.js
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/reducers/__tests__/gnresource-test.js
  geonode_mapstore_client/client/js/reducers/gnresource.js
  geonode_mapstore_client/client/js/routes/Detail.jsx
Labels: bug, Backport, 4.x

#1133 [Fixes 1122] Issues with pressing Enter in Clone dialog
  geonode_mapstore_client/client/js/plugins/save/SaveModal.jsx
Labels: bug, BackportNeeded, 4.x, master

#1140 [Backport 4.x][Fixes 1122] Issues with pressing Enter in Clone dialog
  geonode_mapstore_client/client/js/plugins/save/SaveModal.jsx
Labels: bug, enhancement, 4.x

#1145 [Fixes 1136] The client should only depend on the new favorite field in resource object
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/epics/favorite.js
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/reducers/__tests__/gnresource-test.js
  geonode_mapstore_client/client/js/reducers/gnresource.js
  geonode_mapstore_client/client/js/routes/Detail.jsx
Labels: BackportNeeded, 4.x, master

#1142 [Fixes 1022] Thumbnail placeholders
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
  geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
  geonode_mapstore_client/client/js/routes/Detail.jsx
  geonode_mapstore_client/client/js/routes/Search.jsx
  geonode_mapstore_client/client/js/routes/Viewer.jsx
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
  geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
Labels: enhancement, BackportNeeded, master

#1146 [Fixes 1132] Metadata download
  geonode_mapstore_client/client/js/actions/gndownload.js
  geonode_mapstore_client/client/js/epics/__tests__/gndownload-test.js
  geonode_mapstore_client/client/js/epics/gndownload.js
  geonode_mapstore_client/client/js/plugins/downloads/DublinCoreDownload.jsx
  geonode_mapstore_client/client/js/plugins/downloads/IsoDownload.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/js/reducers/__tests__/gndownload-test.js
  geonode_mapstore_client/client/js/reducers/gndownload.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: enhancement, BackportNeeded, master

#1157 [Fixes 1156] Rename Export and Rearrange Download menu items
  geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: BackportNeeded, master

#1154 [Backport 4.x] [Fixes #1022] Thumbnail placeholders
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
  geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
  geonode_mapstore_client/client/js/routes/Detail.jsx
  geonode_mapstore_client/client/js/routes/Search.jsx
  geonode_mapstore_client/client/js/routes/Viewer.jsx
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
  geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
Labels: enhancement, Backport, 4.x

#1162 [Fixes #1156] Remove duplicated data download plugin
  geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: BackportNeeded, master

#1161 [Fixes #1117] Layer legend is not updated
  geonode_mapstore_client/client/js/plugins/Legend.jsx
Labels: BackportNeeded, master

#1164 [Backport 4.x][Fixes #1117] Layer legend is not updated (#1161)
  geonode_mapstore_client/client/js/plugins/Legend.jsx
Labels: Backport, 4.x

#1165 [Backport 4.x][Fixes #1156] Remove duplicated data download plugin (#1162)
  geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
  geonode_mapstore_client/client/js/plugins/index.js
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: Backport, 4.x
