Repository GeoNode/geonode-mapstore-client, pull requests merged in 2022-03, with the labels that each got.

#855 Download should be visible in card menu to anonymous users if the permission is available
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/ActionButtons/ActionButtons.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: bug, 4.0.x

#857 Implement action to stop upload transfers
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/routes/UploadDocument.jsx
  geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
  geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
  geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
  geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
  geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
  geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Labels: 4.0.x, master

#862 If a request to delete an upload fails the card must be removed from the uploads list
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
Labels: 4.0.x, master

#870 [Fixes #868] Add default upload parallelism limit inside __GEONODE_CONFIG__
  geonode_mapstore_client/context_processors.py
  geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Labels: master

#882 Geostory editing: investigate if it's possible to maintain the origin when switching between resource type selection
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: 4.0.x, master

#884 Unable to Create Maps, GeosStories and Dashboards
  geonode_mapstore_client/client/js/plugins/SaveAs.jsx
  geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Labels: regression, 4.0.x, master

#885 Adopt Upload API error codes
  geonode_mapstore_client/client/js/routes/UploadDataset.jsx
  geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
  geonode_mapstore_client/client/js/utils/ErrorUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ErrorUtils-test.js
Labels: 4.0.x, master, Client App
