Repository GeoNode/geonode-mapstore-client, pull requests merged in 2023-08, with the labels that each got.

#1506 [Fixes #1505] Replace the GetCapabilitiess WMS link with the dataset OWS URL
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
Labels: backport-4.1.x

#1515 #1514: Info panel region style fix
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Labels: master, 4.1.x

#1503 #1500: Tabs type on filter forms
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
  geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
  geonode_mapstore_client/client/js/components/Tabs/Tabs.jsx
  geonode_mapstore_client/client/js/components/Tabs/index.js
  geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
Labels: enhancement, master

#1499 #1498 - Add image/icon property to filter option
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
  geonode_mapstore_client/client/js/utils/SearchUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/SearchUtils-test.js
  geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
Labels: enhancement, master

#1522 [Fixes #1504] Fix italian tx for Cancel
  geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
Labels: backport-4.1.x

#1524 #1482: Use the available height for the abstract text in a card
  geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
  geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
Labels: enhancement, BackportNeeded, master

#1525 [Backport 4.1.x] #1482: Use the available height for the abstract text in a card (#1524)
  geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
  geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
Labels: enhancement, Backport, 4.1.x

#1537 #1536: Improvements to the layout of the action bar menus
  geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx
  geonode_mapstore_client/client/js/components/Menu/MenuItem.js
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/themes/geonode/less/_menu.less
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
Labels: enhancement, master

#1535 #1521: Save maplayer with additional info
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
Labels: enhancement, master

#1513 #1511 & #1512: Implement links to remote documents and source in details panel
  geonode_mapstore_client/client/.npmrc
  geonode_mapstore_client/client/js/components/ActionButtons/ActionButtons.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/DownloadResource.jsx
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/js/utils/PluginsContextUtils.js
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
Labels: enhancement, master
