Repository GeoNode/geonode-mapstore-client, pull requests merged in 2023-05, with the labels that each got.

#1418 #1416: Display relationships between resources in the details info panel
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsLinkedResources.jsx
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
  geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
  geonode_mapstore_client/client/js/epics/gnresource.js
  geonode_mapstore_client/client/js/reducers/gnresource.js
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
Labels: enhancement, 4.1.x

#1432 #1431: Fix translation for Linked resources tab
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
Labels: bug, 4.1.x

#1442 #1439 - Temporal extent to info panel
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
Labels: enhancement, master

#1452 Fix #1395 Dashboard sync not working
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/epics/__tests__/sync-test.js
  geonode_mapstore_client/client/js/epics/gnsync.js
  geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js
  geonode_mapstore_client/client/js/selectors/resource.js
Labels: master, 4.1.x

#1457 Fix #1456 Multiple requests for linked resources
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/epics/__tests__/detailviewer-test.js
  geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
  geonode_mapstore_client/client/js/epics/detailviewer.js
  geonode_mapstore_client/client/js/epics/gnresource.js
  geonode_mapstore_client/client/js/epics/gnsearch.js
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/js/utils/APIUtils.js
Labels: master, backport-4.1.x

#1458 [Backport 4.1.x] Fix #1395 Dashboard sync not working (#1452)
  geonode_mapstore_client/client/js/api/geonode/v2/index.js
  geonode_mapstore_client/client/js/epics/__tests__/sync-test.js
  geonode_mapstore_client/client/js/epics/gnsync.js
  geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js
  geonode_mapstore_client/client/js/selectors/resource.js
Labels: backport-4.1.x

#1459 [Backport 4.1.x] Fix #1456 Multiple requests for linked resources (#1457)
  geonode_mapstore_client/client/js/actions/gnresource.js
  geonode_mapstore_client/client/js/epics/__tests__/detailviewer-test.js
  geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
  geonode_mapstore_client/client/js/epics/detailviewer.js
  geonode_mapstore_client/client/js/epics/gnresource.js
  geonode_mapstore_client/client/js/epics/gnsearch.js
  geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
  geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
  geonode_mapstore_client/client/js/utils/APIUtils.js
Labels: backport-4.1.x

#1463 Fix #1462 The Format option on the Print tool is present twice
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
Labels: master

#1467 [Backport 4.1.x] Fix #1462 The Format option on the Print tool is present twice (#1463)
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
Labels: 4.1.x
