Repository GeoNode/geonode-mapstore-client, pull requests merged in 2023-04, with the labels that each got.

#1394 Feature/copy UUID link to clipboard
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
Labels: master, 4.1.x

#1407 [Backport 4.0.x][Fix #1397] Resource title is not visible inside the preview panel
  geonode_mapstore_client/client/js/routes/Detail.jsx
Labels: regression, 4.0.x, backport-4.0.x

#1411 #1410: Accordion/facet type option for filter form panel
  geonode_mapstore_client/client/js/components/Accordion/Accordion.jsx
  geonode_mapstore_client/client/js/components/Accordion/index.js
  geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
  geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FilterItems-test.jsx
  geonode_mapstore_client/client/js/components/__tests__/Accordion-test.jsx
  geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
  geonode_mapstore_client/client/themes/geonode/less/_variables.less
Labels: enhancement, 4.1.x

#1413 #1412: DetailView - Add link to the metadata page
  geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
  geonode_mapstore_client/client/js/utils/ResourceUtils.js
  geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
  geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
  geonode_mapstore_client/client/themes/geonode/less/_resources-grid.less
  geonode_mapstore_client/static/mapstore/configs/localConfig.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
  geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
Labels: enhancement, 4.1.x
